### PR TITLE
139 implement routing guards

### PR DESCRIPTION
**Pull request by kphutiyagae**
# Description

Implemented application-wide route guards based on AWS Cognito.

Fixes # 139-implement-routing-guards

### Feature
- Added Route guard functionality.
- Added AuthService methods.
- Added tests for route guards.
- Added tests for AuthService.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Unit tests (For RouteGuard class as well as AuthAPI).

### Test configuration:
- Jest Unit testing.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Shojiki-Lukhozi** [comment]
Is there a way to write tests for the uncovered piece of code? (The route guard service).

**Comment by ryanbasiltrickett** [comment]
Please add specified tests under the test section of the PR

**Review by ryanbasiltrickett — CHANGES_REQUESTED** [review]
Please add specified tests under the test section of the PR, and add labels, milestone, etc

**Comment by kphutiyagae** [comment]
> Please add specified tests under the test section of the PR, and add labels, milestone, etc

Done.

**Review by ryanbasiltrickett — APPROVED** [review]

**Pull request merged**
